version: '3'

services:
  guess-db:
    restart: always
    image: postgres:11.4
    container_name: guess-db
    volumes:
      - /tmp/data/core_db:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - guess-network
  
  guess-redis:
    image: redis:latest
    container_name: guess-redis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    #environment:
    #  - REDIS_PASSWORD=123
    #command: ["redis-server", "--requirepass", "123"]
    networks:
      - guess-network
    
  guess-otel-collector:
    container_name: guess-otel-collector
    image: otel/opentelemetry-collector:latest
    volumes:
      - ./configs/otel-collector-config.yaml:/etc/otel-collector-config.yaml
    ports:
      - "4317:4317" # OTLP
      - "9464:9464" # Prometheus
    networks:
      - guess-network
  
#  guess-sentry:
#    image: sentry:latest
#    container_name: guess-sentry
#    environment:
#      - SENTRY_SECRET_KEY=xV9uDuAp5L
#      - SENTRY_DB_USER=sentry
#      - SENTRY_DB_PASSWORD=sentry
#      - SENTRY_DB_HOST=guess-sentry-db
#      - SENTRY_SERVER_EMAIL=admin@guesscode.com
#      - SENTRY_ADMIN_EMAIL=admin@guesscode.com
#      - SENTRY_ADMIN_PASSWORD=admin
#    ports:
#      - "9000:9000"
#    depends_on:
#      - guess-sentry-db
#    volumes:
#      - sentry-data:/var/lib/sentry/files
#      - ./scripts/initialize_sentry.sh:/etc/sentry/initialize_sentry.sh
#    entrypoint: /bin/sh -c "chmod +x /etc/sentry/initialize_sentry.sh && /etc/sentry/initialize_sentry.sh"
#    networks:
#      - guess-network
    
  guess-sentry-db:
    image: postgres:11.4
    container_name: guess-sentry-db
    ports:
      - "1432:5432"
    environment:
      POSTGRES_USER: sentry
      POSTGRES_PASSWORD: sentry
      POSTGRES_DB: sentry
    volumes:
      - sentry-postgres-data:/var/lib/postgresql/data
    networks:
      - guess-network
        
  guess-loki:
    container_name: guess-loki
    image: grafana/loki:latest
    environment:
      TZ: ${SYSTEM_TIMEZONE:-Europe/Moscow}
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/local-config.yaml
    volumes:
     - ./configs/loki-config.yaml:/etc/loki/local-config.yaml
     #- ./data/loki:/loki
    networks:
      - guess-network
    
  guess-grafana:
    container_name: guess-grafana
    environment:
      - GF_PATHS_PROVISIONING=/etc/grafana/provisioning
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - TZ=${SYSTEM_TIMEZONE:-Europe/Moscow}
    volumes:
      - ./configs/data-sources:/etc/grafana/provisioning/datasources
    image: grafana/grafana:latest
    ports:
      - "3005:3000"
  
networks:
  guess-network:

volumes:
  sentry-data:
  sentry-postgres-data:
  redis-data:
    driver: local