receivers:
  otlp:
    protocols:
      grpc:
      http:

exporters:
  logging:
    loglevel: debug
  prometheus:
    endpoint: "0.0.0.0:9464"
  loki:
    endpoint: "http://loki:3100/loki/api/v1/push"
    labels:
      environment: production

processors:
  batch:
  memory_limiter:

service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [logging, loki]
    metrics:
      receivers: [otlp]
      processors: [batch]
      exporters: [prometheus]
